library(edgeR)

PBS10M <- read.delim("mature.18PBS4M.htseq.txt", header=FALSE, row.names = 1)
PBS9M <- read.delim("mature.18PBS1M.htseq.txt", header=FALSE, row.names = 1)
PBS7M <- read.delim("mature.BK-PBS7.htseq.txt", header=FALSE, row.names = 1)
PBS6F <- read.delim("mature.BK-PBS6.htseq.txt", header=FALSE, row.names = 1)
PBS4F <- read.delim("mature.BK-PBS4.htseq.txt", header=FALSE, row.names = 1)
PBS3M <- read.delim("mature.BK-PBS3.htseq.txt", header=FALSE, row.names = 1)
PBS1F <- read.delim("mature.BK-PBS1.htseq.txt", header=FALSE, row.names = 1)
MIA8M <- read.delim("mature.BK-MIA8.htseq.txt", header=FALSE, row.names = 1)
MIA7F <- read.delim("mature.BK-MIA7.htseq.txt", header=FALSE, row.names = 1)
MIA6F <- read.delim("mature.BK-MIA6.htseq.txt", header=FALSE, row.names = 1)
MIA4F <- read.delim("mature.BK-MIA4.htseq.txt", header=FALSE, row.names = 1)
MIA3M <- read.delim("mature.BK-MIA3.htseq.txt", header=FALSE, row.names = 1)
MIA2M <- read.delim("mature.BK-MIA2.htseq.txt", header=FALSE, row.names = 1)
MIA1F <- read.delim("mature.BK-MIA1.htseq.txt", header=FALSE, row.names = 1)

E18Counts_All = cbind(MIA2M,MIA3M,MIA8M,MIA1F,MIA4F,MIA6F,MIA7F,PBS3M,PBS7M,PBS9M,PBS10M,PBS1F,PBS4F,PBS6F)
colnames(E18Counts_All) <- c("MIA2M","MIA3M","MIA8M","MIA1F","MIA4F","MIA6F","MIA7F","PBS3M","PBS7M","PBS9M","PBS10M","PBS1F","PBS4F","PBS6F")
write.csv(E18Counts_All,file="E18CombinedRibo_RawCounts.csv")

#Eliminate all rows with zero counts and also those Sep, Mar, and non-gene rows, then reload counts matrix. Use same genes for RNA and Ribo seq

E18Counts_All_RNA <- read.csv(file = "E18CombinedRibo_RawCounts.csv",row.names=1)
E18Counts_All <- E18Counts_All[rownames(E18Counts_All_RNA),]
group <- c(1,1,1,2,2,2,2,3,3,3,3,4,4,4)
edgeRCounts_All <- DGEList(counts=E18Counts_All,group=group)
edgeRCounts_All <- calcNormFactors(edgeRCounts_All)
design <- model.matrix(~0+group, data=edgeRCounts_All$samples)
colnames(design) <- levels(edgeRCounts_All$samples$group)
edgeRCounts_All <- estimateDisp(edgeRCounts_All, design)
fitQLF <- glmQLFit(edgeRCounts_All, design)

qlf_MIAMPBSM <- glmQLFTest(fitQLF, contrast=c(-1,0,1,0))
FDR_MIAMPBSM <- p.adjust(qlf_MIAMPBSM$table$PValue, method="BH")
qlf_MIAMPBSM_FDR <- cbind(qlf_MIAMPBSM$table,FDR_MIAMPBSM)
write.table(qlf_MIAMPBSM_FDR, file = "Normalized_EdgeR_Ribo_E18_MIAMPBSM_QValues.tsv", sep="\t", col.names=NA)
qlf_MIAFPBSF <- glmQLFTest(fitQLF, contrast=c(0,-1,0,1))
FDR_MIAFPBSF <- p.adjust(qlf_MIAFPBSF$table$PValue, method="BH")
qlf_MIAFPBSF_FDR <- cbind(qlf_MIAFPBSF$table,FDR_MIAFPBSF)
write.table(qlf_MIAFPBSF_FDR, file = "Normalized_EdgeR_Ribo_E18_MIAFPBSF_QValues.tsv", sep="\t", col.names=NA)
qlf_MIAMMIAF <- glmQLFTest(fitQLF, contrast=c(-1,1,0,0))
FDR_MIAMMIAF <- p.adjust(qlf_MIAMMIAF$table$PValue, method="BH")
qlf_MIAMMIAF_FDR <- cbind(qlf_MIAMMIAF$table,FDR_MIAMMIAF)
write.table(qlf_MIAMMIAF_FDR, file = "Normalized_EdgeR_Ribo_E18_MIAMMIAF_QValues.tsv", sep="\t", col.names=NA)
qlf_PBSMPBSF <- glmQLFTest(fitQLF, contrast=c(0,0,-1,1))
FDR_PBSMPBSF <- p.adjust(qlf_PBSMPBSF$table$PValue, method="BH")
qlf_PBSMPBSF_FDR <- cbind(qlf_PBSMPBSF$table,FDR_PBSMPBSF)
write.table(qlf_PBSMPBSF_FDR, file = "Normalized_EdgeR_Ribo_E18_PBSMPBSF_QValues.tsv", sep="\t", col.names=NA)
qlf_InteractionTerm <- glmQLFTest(fitQLF, contrast=c(-1,1,1,-1))
FDR_InteractionTerm <- p.adjust(qlf_InteractionTerm$table$PValue, method="BH")
qlf_InteractionTerm_FDR <- cbind(qlf_InteractionTerm$table,FDR_InteractionTerm)
write.table(qlf_InteractionTerm_FDR, file = "Normalized_EdgeR_Ribo_E18_InteractionTerm_QValues.tsv", sep="\t", col.names=NA)

